apiVersion: v1
kind: Service
metadata:
  name: {{ include "anchor.fullname" . }}-metrics
  labels:
    {{- include "anchor.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "anchor.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: controller
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
