apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "anchor.fullname" . }}-controller
  labels:
    {{- include "anchor.labels" . | nindent 4 }}
  {{- with .Values.controller.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "anchor.fullname" . }}-node
  labels:
    {{- include "anchor.labels" . | nindent 4 }}
