apiVersion: v1
kind: Pod
metadata:
  name: smsc-sctp
  namespace: anchor-e2e
spec:
  containers:
    - name: sctp
      image: anchor-sctp-e2e:0.2.0
      imagePullPolicy: IfNotPresent
      command: ["sleep", "infinity"]
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          cpu: 100m
          memory: 32Mi
        claims:
          - name: endpoint
            request: endpoint
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 65532
        capabilities:
          drop: ["ALL"]
  resourceClaims:
    - name: endpoint
      resourceClaimName: smsc-sigtran-endpoint
